"""Generates per-image prompts from narration — narrative-driven scene breaks.

Gemini decides how many scenes each section needs based on story beats.
Scenes can have multiple characters, objects, and varied backgrounds —
but ALL use the same flat cartoon style for channel-wide consistency.
"""

import json
import re
from src.gemini_helper import generate_text


def _clean_json(text: str) -> str:
    """Fix common Gemini JSON issues."""
    text = re.sub(r',\s*([}\]])', r'\1', text)
    text = text.strip().strip('﻿')
    return text


def generate_image_prompts(section: dict, duration: float) -> list[dict]:
    """Break a narration section into scene prompts.

    One recurring stick figure character. Gemini decides scene breaks
    based on story beats, topic shifts, and visual variety.
    """
    # Fast cuts for engagement — 2-3 seconds per image, never more
    # Even short sections get at least 1 image
    min_images = max(1, int(duration / 3))    # 1 image per 3 seconds minimum
    max_images = max(min_images, int(duration / 2))  # up to 1 per 2 seconds

    prompt = f"""You are a visual storyboard artist for a YouTube explainer channel.

IMAGE GENERATION CONTEXT:
Images are generated by FLUX via Pollinations.ai. A LOCKED style template wraps your scene description:
"flat 2D cartoon illustration, thick black outlines, solid flat colors, simple minimalist style like OverSimplified YouTube channel, warm earth-toned background, [YOUR SCENE DESCRIPTION], all important subjects centered in middle of frame, clean composition, no gradients, no shading, no photorealism"

LOCKED CHARACTER (use in EVERY scene):
The main character is ALWAYS: "a boy with round head, two dot eyes, straight line mouth, messy brown hair, simple stick body with basic clothing"
— refer to him as "the boy" in scene descriptions. He appears in EVERY scene.
— Other characters (waiter, doctor, taxi driver, etc.) use the same stick-figure style.

Your job is to write ONLY the [SCENE DESCRIPTION] part.

SCENE DESCRIPTION RULES:
- Describe WHO is doing WHAT, with WHAT objects, in WHAT setting
- The boy MUST appear in every scene (he's our recurring character)
- You CAN include ADDITIONAL characters (waiter + boy, doctor + boy, taxi driver, etc.)
- You CAN include varied backgrounds (sushi bar, street, split screen, etc.) — use warm earth tones
- You CAN include props, objects, speech bubbles, text overlays, icons
- CRITICAL: Keep all important subjects CENTERED in the middle 60% of the frame. No key characters or objects at the left/right edges. This is for vertical crop compatibility (Reels/TikTok).
- Do NOT include style instructions (no "flat 2D", "thick outlines", "cartoon style", "solid colors", "minimalist" etc.) — the template handles ALL style
- Do NOT describe the boy's appearance — the template handles that
- Keep descriptions SAFE — no violence, weapons, blood, nudity, or strong emotion words like "angry", "offensive", "insulted", "fighting". Use neutral alternatives (serious, surprised, debating)
- MAX 100 characters per scene description

NARRATION TEXT:
"{section['narration']}"

VISUAL NOTES:
"{section.get('visual_notes', 'Match the narration content')}"

AUDIO DURATION: {duration:.1f} seconds

CRITICAL: This is a FAST-PACED YouTube video. Images change every 2-3 seconds like MrBeast / OverSimplified. More scenes = more engaging. NEVER let one image sit for more than 3 seconds.

Break AGGRESSIVELY into scenes — every new idea, every reaction, every beat gets its OWN image. Err on the side of TOO MANY scenes.

You need {min_images} to {max_images} scenes. Aim for the MAXIMUM.

For each scene provide:
- "image_prompt": SHORT scene description (MAX 100 chars). ACTION + OBJECTS + SETTING. Make each scene visually DISTINCT — different characters, poses, objects, backgrounds. Example: "boy and waiter at sushi bar, boy holding chopsticks with wide eyes, colorful plates on counter"
- "key_phrase": DRAMATIC text overlay (2-6 words). Use CAPS, ellipsis, question marks. Examples: "WAIT WHAT?!", "Two. Dollars.", "THE REAL REASON...", "Mind = BLOWN"
- "duration_hint": 2 to 3 seconds MAXIMUM. Must sum to ~{duration:.0f}s.
- "narration_snippet": First 10-15 words of narration this scene covers.

Return ONLY a JSON array, no markdown:
[{{"image_prompt": "...", "key_phrase": "WAIT WHAT?!", "duration_hint": 2.5, "narration_snippet": "..."}}, ...]"""

    raw = generate_text(prompt)
    if not raw:
        raise ValueError("Gemini returned empty response for image prompts")

    text = raw.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1]
        text = text.rsplit("```", 1)[0]
    text = _clean_json(text)

    try:
        prompts = json.loads(text)
    except json.JSONDecodeError:
        fix_prompt = f"Fix this broken JSON array and return ONLY valid JSON:\n{text}"
        fixed = generate_text(fix_prompt)
        if not fixed:
            raise
        fixed = fixed.strip()
        if fixed.startswith("```"):
            fixed = fixed.split("\n", 1)[1]
            fixed = fixed.rsplit("```", 1)[0]
        fixed = _clean_json(fixed)
        prompts = json.loads(fixed)

    # Validate bounds
    if len(prompts) < min_images:
        while len(prompts) < min_images:
            prompts.append({
                "image_prompt": "boy standing and thinking with question mark floating above head, simple background",
                "key_phrase": "",
                "duration_hint": duration / min_images,
                "narration_snippet": ""
            })
    elif len(prompts) > max_images:
        prompts = prompts[:max_images]

    # Normalize durations to match audio
    raw_total = sum(p.get("duration_hint", 3) for p in prompts)
    if raw_total > 0:
        scale = duration / raw_total
        for p in prompts:
            p["duration_hint"] = round(p.get("duration_hint", 3) * scale, 2)

    return prompts


def generate_all_image_prompts(script: dict, audio_segments: list[dict]) -> list[dict]:
    """Generate image prompts for the entire video."""
    all_prompts = []

    for section, audio_seg in zip(script["sections"], audio_segments):
        duration = audio_seg["duration"]
        section_prompts = generate_image_prompts(section, duration)

        print(f"  🎨 {section['id']}: {duration:.1f}s → {len(section_prompts)} scenes")

        for i, p in enumerate(section_prompts):
            all_prompts.append({
                "image_prompt": p["image_prompt"],
                "key_phrase": p.get("key_phrase", ""),
                "duration_hint": p.get("duration_hint", 3),
                "narration_snippet": p.get("narration_snippet", ""),
                "section_id": section["id"],
                "section_index": audio_segments.index(audio_seg),
                "image_index": i,
                "global_index": len(all_prompts),
            })

    print(f"  🎨 Total scenes: {len(all_prompts)}")
    return all_prompts
