"""Generates per-image prompts from narration — narrative-driven scene breaks.

Gemini decides how many scenes each section needs based on story beats.
All scenes use one recurring stick figure character (OverSimplified style).
"""

import json
import re
from src.config import IMAGE_STYLE
from src.gemini_helper import generate_text


def _clean_json(text: str) -> str:
    """Fix common Gemini JSON issues."""
    text = re.sub(r',\s*([}\]])', r'\1', text)
    text = text.strip().strip('﻿')
    return text


def generate_image_prompts(section: dict, duration: float) -> list[dict]:
    """Break a narration section into scene prompts.

    One recurring stick figure character. Gemini decides scene breaks
    based on story beats, topic shifts, and visual variety.
    """
    # Fast cuts for engagement — 2-3 seconds per image, never more
    # Even short sections get at least 1 image
    min_images = max(1, int(duration / 3))    # 1 image per 3 seconds minimum
    max_images = max(min_images, int(duration / 2))  # up to 1 per 2 seconds

    prompt = f"""You are a visual storyboard artist for a YouTube explainer channel.

IMAGE GENERATION CONTEXT:
Images are generated by Cloudflare FLUX Schnell using this LOCKED prompt template:
"cartoon character in center of white background, character takes up 60 percent of frame height, flat 2D cartoon boy with round eyes [YOUR SCENE DESCRIPTION HERE], thick black outlines, solid flat colors, pure white background, clean negative space around edges, simple minimalist composition"

Your job is to write ONLY the [SCENE DESCRIPTION] part — the action, objects, and context.
Do NOT include any style instructions (no "flat 2D", "thick outlines", "white background" etc.)
Just describe WHAT the character is doing and what's around them.
Keep descriptions SAFE — no violence, weapons, or strong emotions words like "angry" or "offensive". Use neutral alternatives.

NARRATION TEXT:
"{section['narration']}"

VISUAL NOTES:
"{section.get('visual_notes', 'Match the narration content')}"

AUDIO DURATION: {duration:.1f} seconds

CRITICAL: This is a FAST-PACED YouTube video. Images change every 2-3 seconds like MrBeast / OverSimplified. More scenes = more engaging. NEVER let one image sit for more than 3 seconds.

Break AGGRESSIVELY into scenes — every new idea, every reaction, every beat gets its OWN image. Err on the side of TOO MANY scenes.

You need {min_images} to {max_images} scenes. Aim for the MAXIMUM.

For each scene provide:
- "image_prompt": SHORT scene description (MAX 100 chars). ACTION + OBJECTS only. Make each scene visually DISTINCT from the last — different pose, different objects, different composition. Example: "eating sushi with chopsticks, eyes wide, sparkling plates of food on table"
- "key_phrase": DRAMATIC text overlay (2-6 words). Use CAPS, ellipsis, question marks. Examples: "WAIT WHAT?!", "Two. Dollars.", "THE REAL REASON...", "Mind = BLOWN"
- "duration_hint": 2 to 3 seconds MAXIMUM. Must sum to ~{duration:.0f}s.
- "narration_snippet": First 10-15 words of narration this scene covers.

Return ONLY a JSON array, no markdown:
[{{"image_prompt": "...", "key_phrase": "WAIT WHAT?!", "duration_hint": 2.5, "narration_snippet": "..."}}, ...]"""

    raw = generate_text(prompt)
    if not raw:
        raise ValueError("Gemini returned empty response for image prompts")

    text = raw.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1]
        text = text.rsplit("```", 1)[0]
    text = _clean_json(text)

    try:
        prompts = json.loads(text)
    except json.JSONDecodeError:
        fix_prompt = f"Fix this broken JSON array and return ONLY valid JSON:\n{text}"
        fixed = generate_text(fix_prompt)
        if not fixed:
            raise
        fixed = fixed.strip()
        if fixed.startswith("```"):
            fixed = fixed.split("\n", 1)[1]
            fixed = fixed.rsplit("```", 1)[0]
        fixed = _clean_json(fixed)
        prompts = json.loads(fixed)

    # Validate bounds
    if len(prompts) < min_images:
        while len(prompts) < min_images:
            prompts.append({
                "image_prompt": "stick figure character thinking with question mark above head",
                "key_phrase": "",
                "duration_hint": duration / min_images,
                "narration_snippet": ""
            })
    elif len(prompts) > max_images:
        prompts = prompts[:max_images]

    # Normalize durations to match audio
    raw_total = sum(p.get("duration_hint", 3) for p in prompts)
    if raw_total > 0:
        scale = duration / raw_total
        for p in prompts:
            p["duration_hint"] = round(p.get("duration_hint", 3) * scale, 2)

    return prompts


def generate_all_image_prompts(script: dict, audio_segments: list[dict]) -> list[dict]:
    """Generate image prompts for the entire video."""
    all_prompts = []

    for section, audio_seg in zip(script["sections"], audio_segments):
        duration = audio_seg["duration"]
        section_prompts = generate_image_prompts(section, duration)

        print(f"  🎨 {section['id']}: {duration:.1f}s → {len(section_prompts)} scenes")

        for i, p in enumerate(section_prompts):
            all_prompts.append({
                "image_prompt": p["image_prompt"],
                "key_phrase": p.get("key_phrase", ""),
                "duration_hint": p.get("duration_hint", 3),
                "narration_snippet": p.get("narration_snippet", ""),
                "section_id": section["id"],
                "section_index": audio_segments.index(audio_seg),
                "image_index": i,
                "global_index": len(all_prompts),
            })

    print(f"  🎨 Total scenes: {len(all_prompts)}")
    return all_prompts
